CREATE TABLE `tb_coupon` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `coupon_name` varchar(64) NOT NULL COMMENT '优惠券名称',
  `coupon_package_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '券包id',
  `use_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '使用类型 1.免费 2.付费',
  `price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '价格',
  `person_limit` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '每人可领张数/券包包含数量',
  `order_limit` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '订单可以使用张数',
  `type_id` tinyint(4) unsigned NOT NULL COMMENT '优惠券类型',
  `start_time` datetime NOT NULL COMMENT '生效时间',
  `end_time` datetime NOT NULL COMMENT '失效时间',
  `pending_time` datetime DEFAULT NULL COMMENT '预热时间',
  `is_shared` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否共享',
  `issue_total_amount` int(11) unsigned NOT NULL COMMENT '发券总数量',
  `issue_start_time` datetime NOT NULL COMMENT '发券开始时间',
  `issue_end_time` datetime NOT NULL COMMENT '发券结束时间',
  `promotion_amount` decimal(12,2) DEFAULT NULL COMMENT '促销金额',
  `order_full_amount` decimal(12,2) DEFAULT NULL COMMENT '订单满金额',
  `promotion_max_amount` decimal(12,2) DEFAULT NULL COMMENT '促销封顶金额',
  `discount_amount` decimal(4,2) DEFAULT NULL COMMENT '折扣金额',
  `gift_name` varchar(64) DEFAULT NULL COMMENT '赠品名称',
  `promotion_scope_amount` varchar(1024) DEFAULT NULL COMMENT '订单金额范围及促销金额JSON',
  `image_url` varchar(200) NOT NULL DEFAULT '' COMMENT '券图片地址',
  `common_status` tinyint(4) unsigned NOT NULL COMMENT '状态',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '删除：1.已删除，0.未删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='优惠券表';
CREATE TABLE `tb_user_coupon` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_id` bigint(20) NOT NULL COMMENT '用户openId',
  `coupon_id` bigint(20) unsigned NOT NULL COMMENT '优惠券id',
  `coupon_code` varchar(16) NOT NULL COMMENT '券码',
  `mobile` varchar(16) NOT NULL COMMENT '手机号',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `common_status` tinyint(4) unsigned NOT NULL COMMENT '状态',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_coupon_code` (`coupon_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户优惠券表';
